[package]
name = "cargo-bylaw"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Cargo subcommand for enforcing Rust architecture rules"

[dependencies]
bylaw = { version = "0.1.0", path = "../bylaw" }
camino.workspace = true
clap.workspace = true
serde_json.workspace = true

[lints]
workspace = true
